import fs from 'fs';
import ejs from 'ejs';
import type { Paragraph } from './parser.js';

const TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= title %></title>
  <style>
    :root {
      --bg: #fcfcfc;
      --text: #1a1a1a;
      --link: #065fd4;
      --link-hover: #00368a;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #111111;
        --text: #e5e5e5;
        --link: #3ea6ff;
        --link-hover: #83c6ff;
      }
    }
    body {
      margin: 0;
      padding: 1rem 0 3rem 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      font-size: 18px;
      line-height: 1.6;
      background-color: var(--bg);
      color: var(--text);
      letter-spacing: -0.01em;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    a {
      color: var(--link);
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
    
    .header-container {
      display: grid;
      grid-template-columns: minmax(0, 800px) min(65ch, 100%);
      gap: 3rem;
      justify-content: end;
      padding-left: 2rem;
      padding-right: max(2rem, calc(50vw - 480px));
      margin-bottom: 2rem;
    }
    .header-content {
      grid-column: 2;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 0.9rem;
      opacity: 0.8;
      width: 100%;
    }
    .video-title {
      font-weight: 600;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      margin-right: 1rem;
    }

    .scene {
      display: grid;
      grid-template-columns: minmax(0, 800px) min(65ch, 100%);
      gap: 3rem;
      justify-content: end;
      align-items: start;
      padding-left: 2rem;
      padding-right: max(2rem, calc(50vw - 480px));
      margin-bottom: 5rem;
    }
    .visuals-column {
      position: sticky;
      top: 2rem;
      max-height: calc(100vh - 4rem);
      display: flex;
      flex-direction: column;
      justify-content: center;
    }
    .text-column {
      max-width: 65ch;
    }
    .bento-grid {
      display: grid;
      gap: 0.75rem;
    }
    .bento-grid[data-count="1"] {
      grid-template-columns: 1fr;
    }
    .bento-grid[data-count="2"] {
      grid-template-columns: 1fr 1fr;
    }
    .bento-grid[data-count="3"] {
      grid-template-columns: 1fr 1fr;
    }
    .bento-grid[data-count="3"] > div:first-child {
      grid-column: span 2;
    }
    .bento-grid[data-count="4"] {
      grid-template-columns: 1fr 1fr;
    }
    
    button.lightbox-trigger {
      background: none;
      border: none;
      padding: 0;
      width: 100%;
      text-align: left;
    }
    
    .bento-grid img {
      width: 100%;
      height: 100%;
      aspect-ratio: 16 / 9;
      object-fit: cover;
      display: block;
      border-radius: 8px;
      cursor: pointer;
      transition: transform 0.2s;
      border: 1px solid rgba(128,128,128,0.2);
    }
    .bento-grid button.lightbox-trigger:hover img {
      transform: scale(1.02);
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }

    .prose p {
      margin: 0 0 1.5rem 0;
      text-wrap: pretty;
    }
    .anchor {
      color: inherit;
      margin-left: 0.5rem;
      opacity: 0;
      transition: opacity 0.2s;
      font-size: 0.85em;
      text-decoration: none;
    }
    .prose p:hover .anchor, .anchor:focus {
      opacity: 0.5;
    }
    .anchor:hover {
      opacity: 1 !important;
      text-decoration: underline;
    }
    
    .lightbox {
      display: none;
      position: fixed;
      top: 0; left: 0; width: 100%; height: 100%;
      background: rgba(0,0,0,0.9);
      z-index: 9999;
      align-items: center;
      justify-content: center;
      cursor: zoom-out;
    }
    .lightbox.active {
      display: flex;
    }
    .lightbox img {
      max-width: 90%;
      max-height: 90vh;
      border-radius: 8px;
    }

    @media (max-width: 600px) {
      .scene, .header-container {
        grid-template-columns: 1fr;
      }
      .header-content {
        grid-column: 1;
      }
      .visuals-column {
        position: relative;
        top: 0;
        margin-bottom: 2rem;
      }
    }
  </style>
</head>
<body>
  <header class="header-container">
    <div class="header-content">
      <span class="video-title" title="<%= title %>"><%= title %></span>
      <span class="credits">Generated by <a href="https://github.com/abstraction/youtube.txt" target="_blank">YouTube.txt</a></span>
    </div>
  </header>
  <main>
    <% chapters.forEach(chapter => { 
         const sceneImages = chapter.uniqueScenes.slice(0, 4);
    %>
      <div class="scene">
        <div class="visuals-column">
          <div class="bento-container">
            <div class="bento-grid" data-count="<%= sceneImages.length %>">
              <% sceneImages.forEach(sceneTs => { %>
                <div>
                  <button type="button" class="lightbox-trigger" aria-haspopup="dialog" aria-label="Video frame at <%= sceneTs %>s">
                    <img src="images/<%= sceneTs %>.jpg" alt="Video frame at <%= sceneTs %>s" loading="lazy">
                  </button>
                </div>
              <% }) %>
            </div>
          </div>
        </div>
        <div class="text-column prose">
          <% chapter.paragraphs.forEach(p => { 
               const linkChar = url.includes('?') ? '&' : '?';
               const timestampUrl = \`\${url}\${linkChar}t=\${Math.floor(p.seconds)}\`;
               let timeLabel = p.timestamp.replace(/^\\d{2}:/, '');
               timeLabel = timeLabel.split('.')[0];
          %>
            <p><%= p.text %> <a href="<%= timestampUrl %>" target="_blank" class="anchor" title="Jump to <%= p.timestamp %>"><%= timeLabel %></a></p>
          <% }) %>
        </div>
      </div>
    <% }) %>
  </main>

  <div class="lightbox" id="lightbox" role="dialog" aria-modal="true" aria-label="Image fullscreen view">
    <img src="" id="lightbox-img">
  </div>
  
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const lightbox = document.getElementById('lightbox');
      const lightboxImg = document.getElementById('lightbox-img');
      
      document.querySelectorAll('.lightbox-trigger').forEach(btn => {
        btn.addEventListener('click', () => {
          const img = btn.querySelector('img');
          if (img) {
            lightboxImg.src = img.src;
            lightbox.classList.add('active');
          }
        });
      });
      
      lightbox.addEventListener('click', () => {
        lightbox.classList.remove('active');
      });
      document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape' && lightbox.classList.contains('active')) {
          lightbox.classList.remove('active');
        }
      });
    });
  </script>
</body>
</html>
`;

export async function generateHtml(url: string, paragraphs: Paragraph[], title: string = 'YouTube Transcript'): Promise<void> {
  const chapters: { uniqueScenes: string[], paragraphs: Paragraph[] }[] = [];
  
  let currentChunk: Paragraph[] = [];
  let currentScenes = new Set<string>();

  for (let i = 0; i < paragraphs.length; i++) {
    const p = paragraphs[i];
    currentChunk.push(p);
    if (p.sceneTimestamp) {
      currentScenes.add(p.sceneTimestamp);
    }
    
    // Check if we should split
    const nextP = paragraphs[i + 1];
    if (nextP) {
      // We only split if the scene is visibly changing to a NEW scene
      const isNewScene = nextP.sceneTimestamp !== p.sceneTimestamp;
      // Ensure the text block has enough vertical height to roughly match the images
      const meetsMinLength = currentChunk.length >= 4;
      
      if (meetsMinLength && isNewScene) {
        chapters.push({
          uniqueScenes: Array.from(currentScenes),
          paragraphs: currentChunk
        });
        currentChunk = [];
        currentScenes = new Set<string>();
      }
    }
  }
  
  if (currentChunk.length > 0) {
    chapters.push({
      uniqueScenes: Array.from(currentScenes),
      paragraphs: currentChunk
    });
  }

  const html = ejs.render(TEMPLATE, { url, chapters, title });
  fs.writeFileSync('index.html', html, 'utf-8');
}
